name: Build Mac
on:
  workflow_dispatch:
  # Disabled automatic builds on push - can be manually triggered via Actions tab
  # push:
  #   branches:
  #     - meatbeats
jobs:
  build_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout HISE repository
        uses: actions/checkout@v4
        with:
          ref: 'meatbeats'
      - name: Build & Upload HISE.app
        working-directory: ${{ github.workspace }}/tools/auto_build/
        run: sh ./build_mac.sh
      - name: Create zip archive
        run: |
          cd "${{ github.workspace }}/projects/standalone/Builds/MacOSX/build/Release"
          ditto -c -k --keepParent "HISE.app" "HISE.zip"
      - name: Upload HISE.app
        uses: actions/upload-artifact@v4
        with:
          name: "HISE.app"
          path: "${{ github.workspace }}/projects/standalone/Builds/MacOSX/build/Release/HISE.zip"
